[package]
name = "ferro-net"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }
ipnet = "2"
serde = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["fs"] }

[target.'cfg(target_os = "linux")'.dependencies]
aya = { workspace = true }

[target.'cfg(target_os = "linux")'.build-dependencies]
aya-build = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[[test]]
name = "ebpf_abi"
path = "src/ebpf_abi.rs"
