[package]
name = "ferro-mgr"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[lints]
workspace = true

[dependencies]
prost = "0.14"
tonic = { version = "0.14", features = ["transport", "tls-ring"] }
tonic-prost = "0.14"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "sync"] }
tokio-stream = "0.1"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
ipnet = "2"
rusqlite = { version = "0.37", features = ["bundled"] }
sha2 = "0.10"
tempfile = { workspace = true }
base64 = "0.22"
getrandom = "0.3"
ed25519-dalek = "2"
rcgen = { version = "0.14", features = ["pem", "x509-parser"] }
nix = { workspace = true, features = ["user", "socket"] }

[build-dependencies]
tonic-prost-build = "0.14"
prost-build = "0.14"
protoc-bin-vendored = "3"
