[package]
name = "ferro-net-ebpf"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "ferro-net-ebpf"
path = "src/main.rs"
test = false
bench = false

[dependencies]
aya-ebpf = { workspace = true }
network-types = { workspace = true, default-features = false }
