syntax = "proto3";

package runtime.v1;

service RuntimeService {
  rpc Version(VersionRequest) returns (VersionResponse);
  rpc Status(StatusRequest) returns (StatusResponse);
}

service ImageService {
  rpc ListImages(ListImagesRequest) returns (ListImagesResponse);
  rpc ImageStatus(ImageStatusRequest) returns (ImageStatusResponse);
  rpc PullImage(PullImageRequest) returns (PullImageResponse);
  rpc RemoveImage(RemoveImageRequest) returns (RemoveImageResponse);
  rpc ImageFsInfo(ImageFsInfoRequest) returns (ImageFsInfoResponse);
}

message VersionRequest {
  string version = 1;
}

message VersionResponse {
  string version = 1;
  string runtime_name = 2;
  string runtime_version = 3;
  string runtime_api_version = 4;
}

message StatusRequest {
  bool verbose = 1;
}

message StatusResponse {
  RuntimeStatus status = 1;
  map<string, string> info = 2;
}

message RuntimeStatus {
  repeated RuntimeCondition conditions = 1;
}

message RuntimeCondition {
  string type = 1;
  bool status = 2;
  string reason = 3;
  string message = 4;
}

message ListImagesRequest {
  string filter = 1;
}

message Image {
  string id = 1;
  repeated string repo_tags = 2;
  repeated string repo_digests = 3;
  uint64 size = 4;
  string uid = 5;
  string username = 6;
}

message ListImagesResponse {
  repeated Image images = 1;
}

message ImageStatusRequest {
  ImageSpec image = 1;
  bool verbose = 2;
}

message ImageSpec {
  string image = 1;
}

message ImageStatusResponse {
  Image image = 1;
  map<string, string> info = 2;
}

message PullImageRequest {
  ImageSpec image = 1;
  map<string, string> auth = 2;
  string sandbox_config = 3;
}

message PullImageResponse {
  string image_ref = 1;
}

message RemoveImageRequest {
  ImageSpec image = 1;
}

message RemoveImageResponse {}

message ImageFsInfoRequest {}

message FilesystemUsage {
  uint64 timestamp = 1;
  string fs_id = 2;
  string mountpoint = 3;
  uint64 used_bytes = 4;
  uint64 inodes_used = 5;
}

message ImageFsInfoResponse {
  repeated FilesystemUsage image_filesystems = 1;
}
