[package]
name = "ferro-cri"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
prost = "0.12"
prost-types = "0.12"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ferro-core = { path = "../ferro-core" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.11", features = ["transport"] }

[dev-dependencies]
tempfile = { workspace = true }
tower = "0.4"
ed25519-dalek = { version = "2.1", default-features = false, features = ["std"] }
httptest = "0.16"
sha2 = "0.10"

[build-dependencies]
tonic-build = "0.11"
protoc-bin-vendored = "3"
