[package]
name = "ferro-cri"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
prost = "0.14"
prost-types = "0.14"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ferro-core = { path = "../ferro-core" }
ferro-net = { path = "../ferro-net" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.14", features = ["transport"] }
tonic-prost = "0.14"
rusqlite = { version = "0.37", features = ["bundled"] }

[dev-dependencies]
tempfile = { workspace = true }
tower = { version = "0.4", features = ["util"] }
ed25519-dalek = { version = "2.1", default-features = false, features = ["std"] }
httptest = "0.16"
hyper-util = { version = "0.1", features = ["tokio"] }
sha2 = "0.10"
tar = "0.4"

[build-dependencies]
tonic-prost-build = "0.14"
prost-build = "0.14"
protoc-bin-vendored = "3"
